import { StyleSheet, Platform, Dimensions } from 'react-native';

const BRAND_BLUE = '#0F4BD7';
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const MCQScreenStyles = StyleSheet.create<any>({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    padding: 16,
  },
  containerBooks: {
    flex: 1,
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 0,
    minHeight: SCREEN_HEIGHT - 100,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  resultScrollContent: {
    paddingTop: 8,
    paddingBottom: 8,
    paddingHorizontal: 18,
    flexGrow: 1,
  },
  resultHero: {
    alignItems: 'center',
    paddingBottom: 8,
  },
  resultPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    marginBottom: 14,
  },
  resultPillText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  resultHeadline: {
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  resultSubhead: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    maxWidth: 300,
  },
  resultRingWrap: {
    alignItems: 'center',
    paddingTop: 14,
    paddingBottom: 18,
  },
  resultRingShadow: {
    width: 220,
    height: 220,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultRingCenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultRingPercent: {
    fontSize: 48,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  resultRingLabel: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  resultStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
    columnGap: 14,
    paddingTop: 4,
    paddingBottom: 18,
  },
  resultStatCard: {
    width: '47.5%',
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  resultStatIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultStatIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultStatTextCol: {
    flex: 1,
    minWidth: 0,
  },
  resultStatValue: {
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  resultStatLabel: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  resultMasteryCard: {
    justifyContent: 'space-between',
  },
  resultMasteryTitle: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  resultMasterySub: {
    marginTop: 2,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  resultButtonsWrap: {
    marginTop: 'auto',
    paddingTop: 10,
    gap: 14,
  },
  resultButton: {
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultButtonSecondary: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 2,
  },
  resultButtonSecondaryText: {
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.4,
  },
  resultButtonPrimary: {
    shadowColor: BRAND_BLUE,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 4,
  },
  resultButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.6,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  mainContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  formContainer: {
    flex: 1,
    padding: 20,
    borderRadius: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  formContainerBooks: {
    flex: 1,
    padding: 0,
    borderRadius: 0,
    elevation: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowColor: 'transparent',
  },
  formContent: {
    gap: 20,
  },
  formGroup: {
    gap: 8,
  },
  formTitle: {
    paddingTop: 5,
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 30,
    textAlign: 'center',
  },
  formLabel: {
    fontSize: 18,
    fontWeight: '600',
  },
  preSelectedLabel: {
    fontSize: 14,
    fontWeight: '400',
    fontStyle: 'italic',
  },
  formInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  formInputText: {
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    maxHeight: '80%',
    borderRadius: 20,
    padding: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
  },
  modalItemText: {
    fontSize: 16,
  },
  startButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 16,
    borderRadius: 12,
    marginTop: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  startButtonText: {
    fontSize: 18,
    fontWeight: '700',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  breadcrumbContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    marginLeft: -20,
    gap: 8,
  },
  breadcrumbItem: {
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
  },
  breadcrumbText: {
    fontSize: 14,
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  questionContainer: {
    marginBottom: 30,
    marginTop: 20,
  },
  questionText: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
  },
  optionsContainer: {
    gap: 12,
    marginBottom: 30,
  },
  optionContainer: {
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderWidth: 1,
    minHeight: 60,
    position: 'relative',
  },
  optionContent: {
    flexDirection: 'row',
    paddingRight: 50,
    paddingLeft: 16,
    paddingVertical: 16,
    minHeight: 60,
    alignItems: 'flex-start',
  },
  optionId: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    marginRight: 10,
    marginTop: 2,
    flexShrink: 0,
  },
  optionIdText: {
    flex: 1,
    flexWrap: 'wrap',
    fontWeight: '600',
    fontSize: 14,
  },
  optionText: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    flexWrap: 'wrap',
    flexShrink: 1,
    alignSelf: 'stretch',
  },
  explanationContainer: {
    padding: 20,
    borderRadius: 12,
    marginTop: 20,
    marginBottom: 40,
  },
  explanationTitle: {
    marginBottom: 10,
  },
  explanationContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
  },
  answerLetterContainer: {
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  answerLetter: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  explanationTextContainer: {
    flex: 1,
    width: '100%',
  },
  explanationText: {
    lineHeight: 24,
  },
  navigationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    paddingHorizontal: 0,
  },
  navButtonContainer: {
    flex: 1,
    alignItems: 'flex-start',
  },
  navButtonContainerRight: {
    flex: 1,
    alignItems: 'flex-end',
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 8,
  },
  prevButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
  },
  nextButton: {
    backgroundColor: '#6B54AE',
  },
  navButtonDisabled: {
    opacity: 0.5,
  },
  prevButtonText: {
    fontWeight: '700',
  },
  nextButtonText: {
    fontWeight: '700',
  },
  progressTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 12,
  },
  progressContainer: {
    marginTop: 10,
    width: '100%',
  },
  progressBar: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  questionLabelContainer: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
  },
  progressText: {
    fontSize: 14,
    fontWeight: '600',
  },
  answerMessageContainer: {
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
    alignItems: 'center',
  },
  answerMessageText: {
    fontSize: 14,
    fontWeight: '500',
  },
  resultCard: {
    width: '100%',
    alignSelf: 'center',
    borderRadius: 20,
    padding: 12,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    overflow: 'hidden',
    marginTop: 8,
  },
  resultContent: {
    gap: 8,
  },
  trophyContainer: {
    alignItems: 'center',
    paddingVertical: 8,
    backgroundColor: 'transparent',
  },
  scoreText: {
    paddingVertical: 12,
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    backgroundColor: 'transparent',
  },
  percentageContainer: {
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 2,
  },
  percentageText: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  messageContainer: {
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
  },
  messageText: {
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
    fontWeight: '600',
  },
  timerContainer: {
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    marginTop: -4,
  },
  timerText: {
    fontSize: 14,
    fontWeight: '600',
  },
  fireworkContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 0,
    height: 0,
    zIndex: 1000,
  },
  particle: {
    position: 'absolute',
    top: 0,
    left: 0,
    transform: [{ translateX: -20 }, { translateY: -20 }],
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
    gap: 10,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  emptyStateIcon: {
    marginBottom: 25,
  },
  emptyStateTitle: {
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 10,
  },
  emptyStateSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    fontWeight: '500',
    opacity: 0.8,
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 12,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '700',
  },
  button: {
    width: '100%',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  homeButton: {
    borderWidth: 2,
  },
  homeButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  examTypeContainer: {
    gap: 16,
    marginTop: 8,
  },
  examTypeButton: {
    width: '100%',
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  examTypeContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  examTypeIcon: {
    flexShrink: 0,
  },
  examTypeTextContainer: {
    flex: 1,
  },
  examTypeText: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 8,
  },
  examTypeDescription: {
    fontSize: 14,
    lineHeight: 20,
  },
  actionButtons: {
    marginTop: 12,
    paddingHorizontal: 16,
  },
  backButton: {
    padding: 8,
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
  },
  selectedSubjectContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  selectedSubjectText: {
    fontSize: 16,
    fontWeight: '600',
  },
  chapterList: {
    maxHeight: 400,
  },
  chapterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
  },
  chapterItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  chapterIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  chapterTextContainer: {
    flex: 1,
  },
  chapterTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  chapterSubtitle: {
    fontSize: 14,
  },
  booksHubScroll: {
    flex: 1,
    alignSelf: 'stretch',
    minHeight: 0,
  },
  booksHubSplit: {
    flex: 1,
    minHeight: 0,
    alignSelf: 'stretch',
    gap: 12,
  },
  booksSearchPanel: {
    marginTop: 10,
    borderRadius: 16,
    borderWidth: 0,
    padding: 12,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  booksListPanel: {
    flex: 1,
    minHeight: 0,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  booksHubListBody: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 12,
  },
  booksNationalLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 0,
    alignSelf: 'flex-start',
  },
  booksNationalLinkText: {
    fontSize: 14,
    fontWeight: '600',
  },
  booksChapterModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  booksChapterModalCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: Math.round(SCREEN_HEIGHT * 0.72),
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    overflow: 'hidden',
  },
  booksChapterModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  booksChapterModalDivider: {
    height: StyleSheet.hairlineWidth,
    width: '100%',
  },
  booksChapterBody: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
  },
  booksChapterModalHeaderTitle: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.2,
    color: BRAND_BLUE,
    marginBottom: 0,
  },
  booksChapterModalTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  booksChapterModalSubtitle: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: -0.1,
  },
  booksChapterModalSubject: {
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '800',
    letterSpacing: -0.2,
    color: BRAND_BLUE,
  },
  booksChapterEitherActions: {
    gap: 12,
    paddingTop: 4,
  },
  booksChapterEitherPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    minHeight: 52,
  },
  booksChapterGridScroll: {
    maxHeight: Math.round(SCREEN_HEIGHT * 0.62),
    alignSelf: 'stretch',
  },
  booksChapterGridScrollContent: {
    width: '100%',
    flexGrow: 1,
    paddingBottom: 4,
  },
  booksChapterGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    paddingBottom: 8,
  },
  booksChapterGridEmpty: {
    width: '100%',
    textAlign: 'center',
    paddingVertical: 24,
    fontSize: 15,
  },
  booksChapterGridCell: {
    flexDirection: 'column',
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 6,
    paddingVertical: 6,
    minHeight: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  booksChapterTile: {
    width: '100%',
    aspectRatio: 1,
    maxHeight: 70,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  booksChapterGridCellIndex: {
    alignSelf: 'center',
    marginBottom: 0,
    minWidth: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  booksChapterGridCellIndexText: {
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  booksChapterTileLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: -0.1,
    minHeight: 32,
  },
  booksChapterGridCellText: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    textAlign: 'center',
  },
  booksSearchField: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 11 : 9,
    borderRadius: 12,
    borderWidth: 0,
  },
  booksSearchInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
    minHeight: 22,
    letterSpacing: 0.15,
  },
  booksChipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 0,
    paddingRight: 4,
    minHeight: 40,
  },
  booksChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
  },
  booksChipLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  bookRowCard: {
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: 18,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  bookRowImageWrap: {
    width: '100%',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
  },
  bookRowBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: BRAND_BLUE,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  bookRowBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  bookRowNoImageText: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  bookRowNoImageTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
  },
  bookRowNoImageSubtitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 6,
  },
  bookRowBody: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 6,
  },
  bookRowTitle: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  bookRowDesc: {
    fontSize: 14,
    lineHeight: 20,
  },
  bookRowActions: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 16,
  },
  bookRowPillFilled: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: BRAND_BLUE,
    shadowColor: BRAND_BLUE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  bookRowPillTextOnBlue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  booksEmpty: {
    textAlign: 'center',
    marginTop: 24,
    fontSize: 15,
  },
  bookDetailScrollContent: {
    paddingBottom: 28,
    paddingHorizontal: 16,
    paddingTop: 0,
    gap: 10,
  },
  bookDetailBackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  bookDetailBackLabel: {
    fontSize: 17,
    fontWeight: '600',
  },
  bookDetailCard: {
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 4,
  },
  bookDetailImageWrap: {
    width: '100%',
    backgroundColor: '#E5E7EB',
  },
  bookDetailBody: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 16,
    gap: 8,
  },
  bookDetailTitle: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.35,
    lineHeight: 28,
  },
  bookDetailDesc: {
    fontSize: 15,
    lineHeight: 22,
  },
  bookDetailActions: {
    marginTop: 8,
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  mcqQuestionContainer: {
    paddingTop: 20,
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  questionModeInnerContent: {
    padding: 0,
  },
  sessionProgressSection: {
    paddingTop: 0,
    paddingBottom: 10,
    paddingHorizontal: 16,
  },
  sessionProgressTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sessionProgressLabel: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  sessionProgressCount: {
    fontSize: 13,
    fontWeight: '800',
  },
  sessionProgressBarTrack: {
    height: 6,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 14,
  },
  sessionProgressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  timeBoxesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  timeBox: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  timeValueText: {
    fontSize: 22,
    fontWeight: '900',
    color: BRAND_BLUE,
    letterSpacing: 0.2,
  },
  timeLabelText: {
    fontSize: 11,
    fontWeight: '700',
    marginTop: 6,
    color: '#6B7280',
  },
  questionScrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 70,
  },
  questionModeBody: {
    flex: 1,
  },
  bottomActionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 12,
    paddingTop: 12,
    paddingBottom: 8,
    paddingHorizontal: 16,
  },
  bottomSecondaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  bottomSecondaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: BRAND_BLUE,
  },
  bottomPrimaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: BRAND_BLUE,
  },
  bottomPrimaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  optionCheckIcon: {
    position: 'absolute',
    right: 16,
    top: '50%',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: BRAND_BLUE,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateY: -11 }],
  },
});
