import { StyleSheet } from 'react-native';

export const ProfileScreenStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  brandMark: {
    width: 50,
    height: 44,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleWrap: { flex: 1, alignItems: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '800' },
  headerRightWrap: { width: 40, alignItems: 'flex-end' },
  scrollContent: { padding: 16, paddingBottom: 28 },
  hero: { alignItems: 'center', paddingBottom: 12 },
  avatarWrap: { marginTop: 6, marginBottom: 12 },
  avatarRing: {
    width: 106,
    height: 106,
    borderRadius: 53,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 46,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: { width: '100%', height: '100%' },
  avatarCamera: {
    position: 'absolute',
    right: -2,
    bottom: 6,
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  name: { fontSize: 20, fontWeight: '900', marginBottom: 4 },
  memberRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 14 },
  memberText: { fontSize: 12, fontWeight: '700' },
  primaryBtn: {
    width: '88%',
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  groupLabel: { marginTop: 18, marginBottom: 8, fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  groupCard: {
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  row: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
  rowIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowText: { flex: 1 },
  rowTitle: { fontSize: 15, fontWeight: '800' },
  rowSubtitle: { marginTop: 2, fontSize: 12, fontWeight: '600' },
  divider: { height: StyleSheet.hairlineWidth, marginLeft: 66 },
  signOutBtn: {
    marginTop: 22,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  signOutText: { fontSize: 14, fontWeight: '800' },
  footerText: { marginTop: 12, textAlign: 'center', fontSize: 12, fontWeight: '600' },
  modalSafe: { flex: 1 },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
  },
  modalTitle: { flex: 1, fontSize: 16, fontWeight: '900', textAlign: 'center' },
  aboutCard: {
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 16,
    gap: 10,
  },
  aboutTitle: {
    fontSize: 18,
    fontWeight: '900',
  },
  aboutSub: {
    fontSize: 13,
    fontWeight: '700',
  },
  aboutBody: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
});
