import { useCallback, useEffect, useRef } from 'react';
import { Audio } from 'expo-av';

// Bundled, offline sound effects (generated by scripts/gen-quiz-sounds.mjs).
const CORRECT_SOUND = require('@/assets/sounds/correct.wav');
const WRONG_SOUND = require('@/assets/sounds/wrong.wav');

export function useQuizSounds(soundEnabled: boolean) {
  const correctSoundRef = useRef<Audio.Sound | null>(null);
  const incorrectSoundRef = useRef<Audio.Sound | null>(null);

  // Preload both effects once so playback is instant when an answer is chosen.
  useEffect(() => {
    let mounted = true;

    (async () => {
      try {
        await Audio.setAudioModeAsync({ playsInSilentModeIOS: true });
        const correct = await Audio.Sound.createAsync(CORRECT_SOUND, { volume: 0.7 });
        const wrong = await Audio.Sound.createAsync(WRONG_SOUND, { volume: 0.7 });
        if (mounted) {
          correctSoundRef.current = correct.sound;
          incorrectSoundRef.current = wrong.sound;
        } else {
          await correct.sound.unloadAsync();
          await wrong.sound.unloadAsync();
        }
      } catch {
        // Audio is best-effort; ignore load failures.
      }
    })();

    return () => {
      mounted = false;
      correctSoundRef.current?.unloadAsync().catch(() => {});
      incorrectSoundRef.current?.unloadAsync().catch(() => {});
      correctSoundRef.current = null;
      incorrectSoundRef.current = null;
    };
  }, []);

  const playCorrectSound = useCallback(async () => {
    if (!soundEnabled) return;
    try {
      await correctSoundRef.current?.replayAsync();
    } catch {
      // ignore playback errors
    }
  }, [soundEnabled]);

  const playIncorrectSound = useCallback(async () => {
    if (!soundEnabled) return;
    try {
      await incorrectSoundRef.current?.replayAsync();
    } catch {
      // ignore playback errors
    }
  }, [soundEnabled]);

  return {
    playCorrectSound,
    playIncorrectSound,
  };
}
