import { StyleSheet, Platform } from 'react-native';
import { BRAND_BLUE } from './practiceStyleTokens';

export const practiceBookCardsStyles = {
  booksSearchField: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 11 : 9,
    borderRadius: 12,
    borderWidth: 0,
  },
  booksSearchInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
    minHeight: 22,
    letterSpacing: 0.15,
  },
  booksChipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 0,
    paddingRight: 4,
    minHeight: 40,
  },
  booksChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
  },
  booksChipLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  bookRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  bookRowContent: {
    flex: 1,
    justifyContent: 'center',
    gap: 10,
  },
  bookRowImageWrap: {
    width: '100%',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 18,
    paddingBottom: 10,
  },
  bookRowCover: {
    borderRadius: 12,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 5,
  },
  bookRowBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: BRAND_BLUE,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 999,
  },
  bookRowBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  bookRowNoImageText: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  bookRowNoImageTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  bookRowNoImageSubtitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 4,
  },
  bookRowBody: {
    gap: 4,
  },
  bookRowTitle: {
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  bookRowDesc: {
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  bookRowActions: {
    flexDirection: 'row',
    gap: 8,
  },
  bookRowPillFilled: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    minHeight: 40,
    paddingVertical: 9,
    paddingHorizontal: 6,
    borderRadius: 12,
    backgroundColor: BRAND_BLUE,
    shadowColor: BRAND_BLUE,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  bookRowPillTextOnBlue: {
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0,
    textAlign: 'center',
  },
  booksEmpty: {
    textAlign: 'center',
    marginTop: 24,
    fontSize: 15,
  },
  bookDetailScrollContent: {
    paddingBottom: 28,
    paddingHorizontal: 16,
    paddingTop: 0,
    gap: 10,
  },
  bookDetailBackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  bookDetailBackLabel: {
    fontSize: 17,
    fontWeight: '600',
  },
  bookDetailCard: {
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 4,
  },
  bookDetailImageWrap: {
    width: '100%',
    backgroundColor: '#E5E7EB',
  },
  bookDetailBody: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 16,
    gap: 8,
  },
  bookDetailTitle: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.35,
    lineHeight: 28,
  },
  bookDetailDesc: {
    fontSize: 15,
    lineHeight: 22,
  },
  bookDetailActions: {
    marginTop: 8,
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  practiceQuestionContainer: {
    paddingTop: 20,
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  questionModeInnerContent: {
    padding: 0,
  },
  sessionProgressSection: {
    paddingTop: 0,
    paddingBottom: 10,
    paddingHorizontal: 16,
  },
  sessionProgressTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sessionProgressSide: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sessionProgressSideEnd: {
    justifyContent: 'flex-end',
    gap: 10,
  },
  sessionProgressLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
    flexShrink: 1,
  },
  sessionProgressCount: {
    fontSize: 13,
    fontWeight: '800',
  },
  sessionProgressBarTrack: {
    height: 6,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 0,
  },
  sessionProgressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  timeChip: {
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    shadowColor: '#64748B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  timeChipIcon: {
    marginRight: 6,
  },
  timeValueText: {
    fontSize: 14,
    fontWeight: '900',
    color: BRAND_BLUE,
    letterSpacing: 1,
    fontVariant: ['tabular-nums'],
  },
  questionScrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 70,
  },
  questionModeBody: {
    flex: 1,
  },
  bottomActionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 12,
    paddingTop: 12,
    paddingBottom: 8,
    paddingHorizontal: 16,
  },
  bottomSecondaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  bottomSecondaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: BRAND_BLUE,
  },
  bottomPrimaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: BRAND_BLUE,
  },
  bottomPrimaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  optionCheckIcon: {
    position: 'absolute',
    right: 16,
    top: '50%',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: BRAND_BLUE,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateY: -11 }],
  },
};
