import { BRAND_BLUE } from './practiceStyleTokens';

export const practiceResultsStyles = {
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    padding: 16,
  },
  containerBooks: {
    flex: 1,
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  resultScrollContent: {
    paddingTop: 8,
    paddingBottom: 8,
    paddingHorizontal: 18,
    flexGrow: 1,
  },
  resultHero: {
    alignItems: 'center',
    paddingBottom: 8,
  },
  resultPill: {
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 999,
    marginBottom: 8,
  },
  resultPillText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  resultHeadline: {
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  resultSubhead: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    maxWidth: 300,
  },
  resultRingWrap: {
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 10,
  },
  resultRingShadow: {
    width: 156,
    height: 156,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultRingCenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultRingPercent: {
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  resultRingLabel: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  resultStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
    columnGap: 10,
    paddingTop: 2,
    paddingBottom: 10,
  },
  resultStatCard: {
    width: '47.5%',
    borderRadius: 14,
    borderWidth: 1,
    padding: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  resultStatIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultStatIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultStatTextCol: {
    flex: 1,
    minWidth: 0,
  },
  resultStatValue: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  resultStatLabel: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  resultMasteryCard: {
    justifyContent: 'space-between',
  },
  resultMasteryTitle: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: -0.2,
  },
  resultMasterySub: {
    marginTop: 2,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  resultButtonsWrap: {
    marginTop: 'auto',
    paddingTop: 8,
    gap: 10,
  },
  resultButton: {
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultButtonSecondary: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 2,
  },
  resultButtonSecondaryText: {
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.4,
  },
  resultButtonPrimary: {
    shadowColor: BRAND_BLUE,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 4,
  },
  resultButtonPrimaryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.6,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
  },
  mainContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  formContainer: {
    flex: 1,
    padding: 20,
    borderRadius: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  formContainerBooks: {
    flex: 1,
    padding: 0,
    borderRadius: 0,
    elevation: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowColor: 'transparent',
  },
  formContent: {
    gap: 20,
  },
  formGroup: {
    gap: 8,
  },
  formTitle: {
    paddingTop: 5,
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 30,
    textAlign: 'center',
  },
  formLabel: {
    fontSize: 18,
    fontWeight: '600',
  },
  preSelectedLabel: {
    fontSize: 14,
    fontWeight: '400',
    fontStyle: 'italic',
  },
  formInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  formInputText: {
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '80%',
    maxHeight: '80%',
    borderRadius: 20,
    padding: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
  },
  modalItemText: {
    fontSize: 16,
  },
  startButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 16,
    borderRadius: 12,
    marginTop: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  startButtonText: {
    fontSize: 18,
    fontWeight: '700',
  },
};
