import { StyleSheet } from 'react-native';
import { BRAND_BLUE, SCREEN_HEIGHT } from './practiceStyleTokens';

export const practiceBooksStyles = {
  examTypeContainer: {
    gap: 16,
    marginTop: 8,
  },
  examTypeButton: {
    width: '100%',
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  examTypeContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  examTypeIcon: {
    flexShrink: 0,
  },
  examTypeTextContainer: {
    flex: 1,
  },
  examTypeText: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 8,
  },
  examTypeDescription: {
    fontSize: 14,
    lineHeight: 20,
  },
  actionButtons: {
    marginTop: 12,
    paddingHorizontal: 16,
  },
  backButton: {
    padding: 8,
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
  },
  selectedSubjectContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  selectedSubjectText: {
    fontSize: 16,
    fontWeight: '600',
  },
  chapterList: {
    maxHeight: 400,
  },
  chapterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
  },
  chapterItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  chapterIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  chapterTextContainer: {
    flex: 1,
  },
  chapterTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  chapterSubtitle: {
    fontSize: 14,
  },
  booksHubScroll: {
    flex: 1,
    alignSelf: 'stretch',
    minHeight: 0,
  },
  booksHubSplit: {
    flex: 1,
    minHeight: 0,
    alignSelf: 'stretch',
    gap: 12,
  },
  booksSearchPanel: {
    marginTop: 10,
    borderRadius: 16,
    borderWidth: 0,
    padding: 12,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 2,
  },
  booksListPanel: {
    flex: 1,
    minHeight: 0,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  booksHubListBody: {
    paddingHorizontal: 14,
    paddingTop: 12,
    // Clear the bottom tab bar (base height + safe-area inset) so the last
    // rows aren't hidden behind it when the list is long (e.g. the All tab).
    paddingBottom: 100,
    gap: 12,
  },
  booksNationalLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 0,
    alignSelf: 'flex-start',
  },
  booksNationalLinkText: {
    fontSize: 14,
    fontWeight: '600',
  },
  booksChapterModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  booksChapterModalCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: Math.round(SCREEN_HEIGHT * 0.72),
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    overflow: 'hidden',
  },
  booksChapterModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  booksChapterModalDivider: {
    height: StyleSheet.hairlineWidth,
    width: '100%',
  },
  booksChapterBody: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
  },
  booksChapterModalHeaderTitle: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.2,
    color: BRAND_BLUE,
    marginBottom: 0,
  },
  booksChapterModalTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  booksChapterModalSubtitle: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: -0.1,
  },
  booksChapterModalSubject: {
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '800',
    letterSpacing: -0.2,
    color: BRAND_BLUE,
  },
  booksChapterEitherActions: {
    gap: 12,
    paddingTop: 4,
  },
  booksChapterEitherPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    minHeight: 52,
  },
  booksChapterGridScroll: {
    maxHeight: Math.round(SCREEN_HEIGHT * 0.62),
    alignSelf: 'stretch',
  },
  booksChapterGridScrollContent: {
    width: '100%',
    flexGrow: 1,
    paddingBottom: 4,
  },
  booksChapterGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    paddingBottom: 8,
  },
  booksChapterGridEmpty: {
    width: '100%',
    textAlign: 'center',
    paddingVertical: 24,
    fontSize: 15,
  },
  booksChapterGridCell: {
    flexDirection: 'column',
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 6,
    paddingVertical: 6,
    minHeight: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  booksChapterTile: {
    width: '100%',
    aspectRatio: 1,
    maxHeight: 70,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  booksChapterGridCellIndex: {
    alignSelf: 'center',
    marginBottom: 0,
    minWidth: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  booksChapterGridCellIndexText: {
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  booksChapterTileLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: -0.1,
    minHeight: 32,
  },
  booksChapterGridCellText: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
    textAlign: 'center',
  },
};
