import { StyleSheet } from 'react-native';

export const PlanSelectionScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  bgLettersLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    overflow: 'hidden',
  },
  bgLetter: {
    position: 'absolute',
    fontSize: 360,
    fontWeight: '800',
    lineHeight: 360,
  },
  bgLetterLeft: {
    left: -52,
    top: 44,
    transform: [{ rotate: '-7deg' }],
  },
  bgLetterRight: {
    right: -78,
    bottom: -74,
    transform: [{ rotate: '7deg' }],
  },
  keyboardView: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 8,
    zIndex: 1,
  },
  header: {
    marginBottom: 8,
  },
  backButton: {
    marginBottom: 8,
  },
  languageToggleContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    marginTop: 8,
    marginRight: 16,
    zIndex: 1,
  },
  title: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '700',
    marginBottom: 4,
    marginTop: 6,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginBottom: 2,
  },
  scrollContent: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingBottom: 18,
  },
  plansContainer: {
    gap: 8,
    paddingBottom: 8,
  },
  planCard: {
    borderRadius: 18,
    position: 'relative',
    overflow: 'hidden',
    marginBottom: 8,
    minHeight: 102,
    backgroundColor: 'transparent',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  planAccentBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 6,
    zIndex: 5,
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
  },
  planCardGradient: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
  },
  recommendedBadge: {
    marginLeft: 8,
  },
  badgeGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  planHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  planTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
    paddingRight: 8,
  },
  planName: {
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  priceContainer: {
    alignItems: 'flex-end',
  },
  planPrice: {
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  planDuration: {
    fontSize: 11,
    fontWeight: '600',
    opacity: 0.95,
  },
  descriptionContainer: {
    marginBottom: 6,
  },
  planDescription: {
    fontSize: 12.5,
    lineHeight: 17,
    opacity: 0.9,
    fontWeight: '500',
  },
  remarkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(15, 75, 215, 0.12)',
    borderRadius: 8,
    marginTop: 4,
  },
  planRemark: {
    fontSize: 11,
    flex: 1,
    opacity: 0.95,
    fontWeight: '600',
  },
  recommendedInlineText: {
    fontSize: 12,
    fontWeight: '700',
    opacity: 0.85,
    fontStyle: 'italic',
  },
  activeBorderIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    backgroundColor: 'transparent',
  },
  footer: {
    paddingTop: 12,
    borderTopWidth: 1.5,
    borderTopColor: 'rgba(15, 75, 215, 0.18)',
    backgroundColor: 'transparent',
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  totalAmount: {
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  continueButton: {
    width: '100%',
    height: 54,
    borderRadius: 28,
    overflow: 'hidden',
    opacity: 0.5,
  },
  continueButtonActive: {
    opacity: 1,
  },
  continueButtonProcessing: {
    opacity: 0.8,
  },
  buttonGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingIndicator: {
    marginRight: 8,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});
