import { StyleSheet } from 'react-native';

export const LoginScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  container: {
    flex: 1,
    paddingHorizontal: 10,
    paddingTop: 10,
    justifyContent: 'flex-start',
  },
  bgLettersLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    overflow: 'hidden',
  },
  bgLetter: {
    position: 'absolute',
    fontSize: 360,
    fontWeight: '800',
    lineHeight: 360,
  },
  bgLetterLeft: {
    left: -52,
    top: 44,
    transform: [{ rotate: '-7deg' }],
  },
  bgLetterRight: {
    right: -78,
    bottom: -74,
    transform: [{ rotate: '7deg' }],
  },
  header: {
    position: 'relative',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 22,
    paddingTop: 34,
    zIndex: 1,
  },
  backButton: {
    position: 'absolute',
    top: 6,
    left: 4,
    padding: 8,
    zIndex: 2,
  },
  languageToggleContainer: {
    position: 'absolute',
    top: 6,
    right: 4,
    zIndex: 2,
  },
  brand: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  brandIcon: {
    width: 100,
    height: 100,
    borderRadius: 18,
  },
  formContainer: {
    width: '100%',
    borderRadius: 28,
    paddingHorizontal: 26,
    paddingTop: 28,
    paddingBottom: 30,
    marginBottom: 10,
    zIndex: 1,
  },
  title: {
    fontSize: 32,
    lineHeight: 38,
    textAlign: 'center',
    fontWeight: '700',
    fontFamily: 'System',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 30,
    textAlign: 'center',
    fontFamily: 'System',
    marginBottom: 24,
  },
  fieldLabel: {
    fontSize: 12,
    lineHeight: 16,
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 1.1,
    marginBottom: 8,
    marginLeft: 2,
  },
  inputContainer: {
    borderRadius: 14,
    backgroundColor: '#E9EAED',
    height: 60,
    paddingHorizontal: 18,
    justifyContent: 'center',
    marginBottom: 8,
  },
  input: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '500',
  },
  passwordLabelRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  forgotLink: {
    color: '#0F4BD7',
    fontSize: 14,
    fontWeight: '700',
  },
  passwordInputContainerOverride: {
    marginTop: 4,
    marginBottom: 8,
    borderRadius: 14,
    backgroundColor: '#E9EAED',
    borderWidth: 0,
    height: 60,
  },
  signInButton: {
    width: '100%',
    height: 60,
    borderRadius: 30,
    overflow: 'hidden',
    marginTop: 10,
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 8,
  },
  buttonGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signInInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    width: '100%',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '600',
  },
  inputError: {
    borderWidth: 1,
    borderColor: '#EF4444',
  },
  errorText: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: -2,
    marginBottom: 6,
    marginLeft: 4,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 8,
    zIndex: 1,
  },
  footerText: {
    fontSize: 16,
  },
  signupButton: {
    paddingVertical: 4,
  },
  signupText: {
    color: '#0F4BD7',
    fontSize: 16,
    fontWeight: '700',
  },
  errorMessage: {
    color: '#EF4444',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 12,
    backgroundColor: '#FEE2E2',
    padding: 12,
    borderRadius: 8,
  },
  loginButtonDisabled: {
    opacity: 0.7,
  },
});
