import { EARLY_PICTURE_DROP_TARGET_BORDER_WIDTH } from '../constants/EarlyPictureScreen.constants';
import { KG_DESIGN_TOKENS } from '../constants/DesignTokens';

export const earlyPictureCoreStyles = {
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#fff',
  },
  funContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
  },
  headerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    padding: 8,
    marginRight: 8,
  },
  headerLogo: {
    width: 36,
    height: 30,
    marginBottom: 4,
  },
  profileIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  imageContainer: {
    width: '100%',
    height: 300,
    marginBottom: 20,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    borderWidth: 4,
    borderColor: KG_DESIGN_TOKENS.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 2,
    shadowColor: KG_DESIGN_TOKENS.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  questionImage: {
    width: '100%',
    height: '100%',
  },
  imageErrorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  imageErrorText: {
    marginTop: 12,
    fontSize: 16,
    textAlign: 'center',
  },
  overlayVideoContainer: {
    position: 'absolute',
    top: 8,
    left: 8,
    right: 8,
    bottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  inlineVideo: {
    width: '100%',
    height: '100%',
  },
  fireworkContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    zIndex: 1000,
    overflow: 'visible',
  },
  fireworkOrigin: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fireworkParticle: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fireworkDot: {
    elevation: 10,
  },
  shakeOverlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shakeIconContainer: {
    backgroundColor: 'rgba(255, 100, 100, 0.9)',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  shakeEmoji: {
    fontSize: 48,
    marginBottom: 8,
  },
  shakeText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitleText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#111827',
  },
  kgProgressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 16,
  },
  kgProgressBar: {
    flex: 1,
    height: 14,
    backgroundColor: '#E5E7EB',
    borderRadius: 7,
    overflow: 'hidden',
  },
  kgProgressFill: {
    height: '100%',
    borderRadius: 7,
  },
  kgProgressText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#374151',
    minWidth: 50,
    textAlign: 'right',
  },
  kgOptionsContainer: {
    flexDirection: 'column',
    gap: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  kgOptionButton: {
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 24,
    alignItems: 'center',
    shadowColor: KG_DESIGN_TOKENS.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  kgOptionButtonBounce: {
    transform: [{ scale: 1 }],
  },
  kgOptionButtonHovered: {
    transform: [{ scale: 1.09 }],
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
  },
  kgOptionButtonDimmed: {
    opacity: 0.45,
    transform: [{ scale: 0.97 }],
  },
  kgOptionButtonDropTarget: {
    borderWidth: EARLY_PICTURE_DROP_TARGET_BORDER_WIDTH,
    borderColor: '#FFFFFF',
    shadowColor: '#FFD700',
    shadowOpacity: 0.7,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 14,
  },
  kgOptionText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    flexShrink: 1,
  },
  kgOptionTextAmharic: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    marginLeft: 8,
  },
  optionTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  instructionTextContainer: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  instructionText: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
    opacity: 0.8,
  },
  explanationContainer: {
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
  },
  explanationTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  explanationText: {
    fontSize: 16,
    lineHeight: 24,
  },
  correctText: {
    color: '#2196F3',
    fontWeight: 'bold',
  },
  incorrectText: {
    color: '#D32F2F',
    fontWeight: 'bold',
  },
  settingsButton: {
    marginLeft: 12,
    padding: 4,
  },
  settingsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  settingsModalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  settingsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  settingsModalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#333',
  },
  settingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  settingsLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsLabel: {
    fontSize: 18,
    color: '#333',
    fontWeight: '500',
  },
  settingsToggle: {
    width: 56,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E0E0E0',
    padding: 2,
    justifyContent: 'center',
  },
  settingsToggleActive: {
    backgroundColor: '#2196F3',
  },
  settingsToggleKnob: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  settingsToggleKnobActive: {
    alignSelf: 'flex-end',
  },
  delayOptionsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
    marginBottom: 24,
  },
  delayOption: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
  },
  delayOptionActive: {
    backgroundColor: '#2196F3',
  },
  delayOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
  delayOptionTextActive: {
    color: '#FFFFFF',
  },
  settingsDoneButton: {
    backgroundColor: '#2196F3',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  settingsDoneButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
};
