import { CARD_WIDTH, CARD_HEIGHT, SESSION_RESULTS_RING_SIZE } from './flashcardsStyleTokens';

export const flashcardsCoreStyles = {
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  flashHeaderWrap: {
    backgroundColor: '#FFFFFF',
    paddingBottom: 4,
  },
  flashTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  flashTopLogoLeft: {
    width: 40,
    height: 34,
    marginBottom: 6,
  },
  flashBrandPill: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: '#0F4BD7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F4BD7',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 3,
  },
  flashBrandText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 15,
  },
  flashBrandImg: {
    width: 50,
    height: 44,
  },
  flashTopLogo: {
    width: 50,
    height: 44,
    alignSelf: 'center',
  },
  flashTopTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  flashCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flashProgressBlock: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    paddingTop: 8,
    borderTopWidth: 0,
  },
  flashProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  flashProgressCountRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  flashProgressLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  flashProgressCount: {
    fontSize: 16,
    fontWeight: '800',
  },
  flashProgressCardsSuffix: {
    fontSize: 16,
    fontWeight: '700',
  },
  flashProgressTrack: {
    height: 6,
    borderRadius: 999,
    overflow: 'hidden',
  },
  flashProgressFill: {
    height: '100%',
    borderRadius: 999,
  },
  flashCardStage: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  flashCardTouch: {
    flex: 1,
  },
  flashCardShadowWrap: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    borderRadius: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.10,
    shadowRadius: 28,
    elevation: 6,
  },
  flashCardFace: {
    flex: 1,
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingTop: 26,
    paddingBottom: 18,
    backfaceVisibility: 'hidden',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  flashCardBackFace: {
    transform: [{ rotateY: '180deg' }],
  },
  flashCardMeta: {
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 2.4,
    marginBottom: 18,
    textTransform: 'uppercase',
  },
  flashCardScroll: {
    flex: 1,
  },
  flashCardScrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 18,
  },
  flashCardTitle: {
    fontWeight: '500',
    letterSpacing: -0.4,
  },
  flashTapHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingTop: 10,
  },
  flashTapHintText: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  flashBottomActions: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 26,
    paddingTop: 10,
    paddingBottom: 22,
    marginBottom: 10,
  },
  flashBottomActionLeft: {
    alignItems: 'center',
    gap: 10,
  },
  flashBottomActionRight: {
    alignItems: 'center',
    gap: 10,
  },
  flashBottomIconGhost: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  flashBottomIconPrimary: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F4BD7',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.22,
    shadowRadius: 22,
    elevation: 6,
  },
  flashBottomLabel: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  flashBottomLabelPrimary: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  flashResultsHeader: {
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 10,
  },
  flashResultsBrand: {
    width: 50,
    height: 44,
  },
  flashResultsTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#0F4BD7',
    fontWeight: '800',
    fontSize: 16,
  },
  flashResultsProfileBtn: {
    width: 40,
    alignItems: 'flex-end',
  },
  flashResultsScroll: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 18,
    flexGrow: 1,
  },
  flashRingWrap: {
    alignSelf: 'center',
    width: SESSION_RESULTS_RING_SIZE,
    height: SESSION_RESULTS_RING_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  flashRingCenter: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flashRingPct: {
    fontSize: 34,
    fontWeight: '900',
    color: '#111827',
    letterSpacing: -0.6,
    lineHeight: 40,
  },
  flashRingSub: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 2.4,
    color: '#0F4BD7',
  },
  flashRingBadge: {
    position: 'absolute',
    right: 24,
    top: 14,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#0F4BD7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F4BD7',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 3,
  },
  flashResultCards: {
    gap: 14,
    marginTop: 8,
    marginBottom: 18,
  },
  flashResultCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  flashResultIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flashResultCardText: {
    flex: 1,
  },
  flashResultCardLabel: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 2.2,
    color: '#9AA3B2',
    marginBottom: 6,
  },
  flashResultCardValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
  },
  flashResultButtons: {
    gap: 14,
    paddingTop: 8,
    paddingBottom: 18,
    marginTop: 'auto',
  },
  flashRetryBtn: {
    height: 54,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  flashRetryText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#6B7280',
  },
  flashDoneBtn: {
    height: 58,
    borderRadius: 18,
    backgroundColor: '#0F4BD7',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: '#0F4BD7',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 5,
  },
  flashDoneText: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FFFFFF',
  },
};
